/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ApiAuthRouteImport } from './routes/api.auth'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as CliSigninIndexRouteImport } from './routes/cli.signin.index'
import { Route as ProjectsProjectIdRawFeedbackRouteImport } from './routes/projects.$projectId.raw-feedback'
import { Route as ProjectsProjectIdFeaturesRouteImport } from './routes/projects.$projectId.features'
import { Route as ProjectsProjectIdConfigRouteImport } from './routes/projects.$projectId.config'
import { Route as ProjectsProjectIdFeaturesIndexRouteImport } from './routes/projects.$projectId.features.index'
import { Route as CliSigninCompleteIndexRouteImport } from './routes/cli.signin.complete.index'
import { Route as ProjectsProjectIdFeedbackFeedbackIdRouteImport } from './routes/projects.$projectId.feedback.$feedbackId'
import { Route as ProjectsProjectIdFeaturesFeatureIdRouteImport } from './routes/projects.$projectId.features.$featureId'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const CliSigninIndexRoute = CliSigninIndexRouteImport.update({
  id: '/cli/signin/',
  path: '/cli/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRawFeedbackRoute =
  ProjectsProjectIdRawFeedbackRouteImport.update({
    id: '/raw-feedback',
    path: '/raw-feedback',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdFeaturesRoute =
  ProjectsProjectIdFeaturesRouteImport.update({
    id: '/features',
    path: '/features',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdConfigRoute = ProjectsProjectIdConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdFeaturesIndexRoute =
  ProjectsProjectIdFeaturesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdFeaturesRoute,
  } as any)
const CliSigninCompleteIndexRoute = CliSigninCompleteIndexRouteImport.update({
  id: '/cli/signin/complete/',
  path: '/cli/signin/complete/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdFeedbackFeedbackIdRoute =
  ProjectsProjectIdFeedbackFeedbackIdRouteImport.update({
    id: '/feedback/$feedbackId',
    path: '/feedback/$feedbackId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdFeaturesFeatureIdRoute =
  ProjectsProjectIdFeaturesFeatureIdRouteImport.update({
    id: '/$featureId',
    path: '/$featureId',
    getParentRoute: () => ProjectsProjectIdFeaturesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/api/auth': typeof ApiAuthRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/config': typeof ProjectsProjectIdConfigRoute
  '/projects/$projectId/features': typeof ProjectsProjectIdFeaturesRouteWithChildren
  '/projects/$projectId/raw-feedback': typeof ProjectsProjectIdRawFeedbackRoute
  '/cli/signin': typeof CliSigninIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/features/$featureId': typeof ProjectsProjectIdFeaturesFeatureIdRoute
  '/projects/$projectId/feedback/$feedbackId': typeof ProjectsProjectIdFeedbackFeedbackIdRoute
  '/cli/signin/complete': typeof CliSigninCompleteIndexRoute
  '/projects/$projectId/features/': typeof ProjectsProjectIdFeaturesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/api/auth': typeof ApiAuthRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/config': typeof ProjectsProjectIdConfigRoute
  '/projects/$projectId/raw-feedback': typeof ProjectsProjectIdRawFeedbackRoute
  '/cli/signin': typeof CliSigninIndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/features/$featureId': typeof ProjectsProjectIdFeaturesFeatureIdRoute
  '/projects/$projectId/feedback/$feedbackId': typeof ProjectsProjectIdFeedbackFeedbackIdRoute
  '/cli/signin/complete': typeof CliSigninCompleteIndexRoute
  '/projects/$projectId/features': typeof ProjectsProjectIdFeaturesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/api/auth': typeof ApiAuthRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/config': typeof ProjectsProjectIdConfigRoute
  '/projects/$projectId/features': typeof ProjectsProjectIdFeaturesRouteWithChildren
  '/projects/$projectId/raw-feedback': typeof ProjectsProjectIdRawFeedbackRoute
  '/cli/signin/': typeof CliSigninIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/features/$featureId': typeof ProjectsProjectIdFeaturesFeatureIdRoute
  '/projects/$projectId/feedback/$feedbackId': typeof ProjectsProjectIdFeedbackFeedbackIdRoute
  '/cli/signin/complete/': typeof CliSigninCompleteIndexRoute
  '/projects/$projectId/features/': typeof ProjectsProjectIdFeaturesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/api/auth'
    | '/projects/$projectId'
    | '/projects'
    | '/projects/$projectId/config'
    | '/projects/$projectId/features'
    | '/projects/$projectId/raw-feedback'
    | '/cli/signin'
    | '/projects/$projectId/'
    | '/projects/$projectId/features/$featureId'
    | '/projects/$projectId/feedback/$feedbackId'
    | '/cli/signin/complete'
    | '/projects/$projectId/features/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/api/auth'
    | '/projects'
    | '/projects/$projectId/config'
    | '/projects/$projectId/raw-feedback'
    | '/cli/signin'
    | '/projects/$projectId'
    | '/projects/$projectId/features/$featureId'
    | '/projects/$projectId/feedback/$feedbackId'
    | '/cli/signin/complete'
    | '/projects/$projectId/features'
  id:
    | '__root__'
    | '/'
    | '/signin'
    | '/api/auth'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/config'
    | '/projects/$projectId/features'
    | '/projects/$projectId/raw-feedback'
    | '/cli/signin/'
    | '/projects/$projectId/'
    | '/projects/$projectId/features/$featureId'
    | '/projects/$projectId/feedback/$feedbackId'
    | '/cli/signin/complete/'
    | '/projects/$projectId/features/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninRoute: typeof SigninRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  CliSigninIndexRoute: typeof CliSigninIndexRoute
  CliSigninCompleteIndexRoute: typeof CliSigninCompleteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/cli/signin/': {
      id: '/cli/signin/'
      path: '/cli/signin'
      fullPath: '/cli/signin'
      preLoaderRoute: typeof CliSigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/raw-feedback': {
      id: '/projects/$projectId/raw-feedback'
      path: '/raw-feedback'
      fullPath: '/projects/$projectId/raw-feedback'
      preLoaderRoute: typeof ProjectsProjectIdRawFeedbackRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/features': {
      id: '/projects/$projectId/features'
      path: '/features'
      fullPath: '/projects/$projectId/features'
      preLoaderRoute: typeof ProjectsProjectIdFeaturesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/config': {
      id: '/projects/$projectId/config'
      path: '/config'
      fullPath: '/projects/$projectId/config'
      preLoaderRoute: typeof ProjectsProjectIdConfigRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/features/': {
      id: '/projects/$projectId/features/'
      path: '/'
      fullPath: '/projects/$projectId/features/'
      preLoaderRoute: typeof ProjectsProjectIdFeaturesIndexRouteImport
      parentRoute: typeof ProjectsProjectIdFeaturesRoute
    }
    '/cli/signin/complete/': {
      id: '/cli/signin/complete/'
      path: '/cli/signin/complete'
      fullPath: '/cli/signin/complete'
      preLoaderRoute: typeof CliSigninCompleteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/feedback/$feedbackId': {
      id: '/projects/$projectId/feedback/$feedbackId'
      path: '/feedback/$feedbackId'
      fullPath: '/projects/$projectId/feedback/$feedbackId'
      preLoaderRoute: typeof ProjectsProjectIdFeedbackFeedbackIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/features/$featureId': {
      id: '/projects/$projectId/features/$featureId'
      path: '/$featureId'
      fullPath: '/projects/$projectId/features/$featureId'
      preLoaderRoute: typeof ProjectsProjectIdFeaturesFeatureIdRouteImport
      parentRoute: typeof ProjectsProjectIdFeaturesRoute
    }
  }
}

interface ProjectsProjectIdFeaturesRouteChildren {
  ProjectsProjectIdFeaturesFeatureIdRoute: typeof ProjectsProjectIdFeaturesFeatureIdRoute
  ProjectsProjectIdFeaturesIndexRoute: typeof ProjectsProjectIdFeaturesIndexRoute
}

const ProjectsProjectIdFeaturesRouteChildren: ProjectsProjectIdFeaturesRouteChildren =
  {
    ProjectsProjectIdFeaturesFeatureIdRoute:
      ProjectsProjectIdFeaturesFeatureIdRoute,
    ProjectsProjectIdFeaturesIndexRoute: ProjectsProjectIdFeaturesIndexRoute,
  }

const ProjectsProjectIdFeaturesRouteWithChildren =
  ProjectsProjectIdFeaturesRoute._addFileChildren(
    ProjectsProjectIdFeaturesRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdConfigRoute: typeof ProjectsProjectIdConfigRoute
  ProjectsProjectIdFeaturesRoute: typeof ProjectsProjectIdFeaturesRouteWithChildren
  ProjectsProjectIdRawFeedbackRoute: typeof ProjectsProjectIdRawFeedbackRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdFeedbackFeedbackIdRoute: typeof ProjectsProjectIdFeedbackFeedbackIdRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdConfigRoute: ProjectsProjectIdConfigRoute,
  ProjectsProjectIdFeaturesRoute: ProjectsProjectIdFeaturesRouteWithChildren,
  ProjectsProjectIdRawFeedbackRoute: ProjectsProjectIdRawFeedbackRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsProjectIdFeedbackFeedbackIdRoute:
    ProjectsProjectIdFeedbackFeedbackIdRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninRoute: SigninRoute,
  ApiAuthRoute: ApiAuthRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
  CliSigninIndexRoute: CliSigninIndexRoute,
  CliSigninCompleteIndexRoute: CliSigninCompleteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
