packages:
  - apps/*
  - libs/*

catalog:
  '@ai-sdk/google': 2.0.14
  '@daveyplate/better-auth-ui': ^3.1.10
  '@eslint/js': ^9.36.0
  '@hookform/resolvers': 5.2.2
  '@modelcontextprotocol/sdk': 1.18.1
  '@radix-ui/react-accordion': 1.2.12
  '@radix-ui/react-alert-dialog': 1.1.15
  '@radix-ui/react-aspect-ratio': 1.1.7
  '@radix-ui/react-avatar': 1.1.10
  '@radix-ui/react-checkbox': 1.3.3
  '@radix-ui/react-collapsible': 1.1.12
  '@radix-ui/react-context-menu': 2.2.16
  '@radix-ui/react-dialog': 1.1.15
  '@radix-ui/react-dropdown-menu': 2.1.16
  '@radix-ui/react-hover-card': 1.1.15
  '@radix-ui/react-label': 2.1.7
  '@radix-ui/react-menubar': 1.1.16
  '@radix-ui/react-navigation-menu': 1.2.14
  '@radix-ui/react-popover': 1.1.15
  '@radix-ui/react-progress': 1.1.7
  '@radix-ui/react-radio-group': 1.3.8
  '@radix-ui/react-scroll-area': 1.2.10
  '@radix-ui/react-select': 2.2.6
  '@radix-ui/react-separator': 1.1.7
  '@radix-ui/react-slider': 1.3.6
  '@radix-ui/react-slot': 1.2.3
  '@radix-ui/react-switch': 1.2.6
  '@radix-ui/react-tabs': 1.1.13
  '@radix-ui/react-toggle': 1.1.10
  '@radix-ui/react-toggle-group': 1.1.11
  '@radix-ui/react-tooltip': 1.2.8
  '@tailwindcss/vite': ^4.1.13
  '@tanstack/eslint-config': ^0.3.2
  '@tanstack/react-devtools': ^0.7.2
  '@tanstack/react-router': ^1.132.33
  '@tanstack/react-router-devtools': ^1.132.33
  '@tanstack/router-plugin': ^1.132.33
  '@types/better-sqlite3': ^7.6.13
  '@types/cookie': ^1.0.0
  '@types/cookie-parser': ^1.4.9
  '@types/cors': ^2.8.19
  '@types/express': ^5.0.3
  '@types/node': 24.4.0
  '@types/qs': ^6.14.0
  '@types/react': ^19.1.13
  '@typescript-eslint/eslint-plugin': ^8.45.0
  '@typescript-eslint/parser': ^8.45.0
  '@vitejs/plugin-react': ^5.0.4
  ai: 5.0.44
  better-auth: 1.3.11
  better-sqlite3: ^12.2.0
  chalk: ^5.6.2
  class-variance-authority: 0.7.1
  clsx: ^2.1.1
  cmdk: 1.1.1
  cookie: ^1.0.2
  cookie-parser: ^1.4.7
  cors: ^2.8.5
  date-fns: 4.1.0
  dotenv: 16.6.1
  drizzle-kit: ^0.31.4
  drizzle-orm: 0.44.5
  embla-carousel-react: 8.6.0
  eslint: ^9.36.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-prettier: ^5.5.4
  express: ^5.1.0
  globals: ^16.4.0
  input-otp: 1.4.2
  lucide-react: 0.476.0
  next-themes: 0.4.6
  postgres: ^3.4.5
  prettier: ^3.6.2
  qs: ^6.14.0
  react: ^19.1.1
  react-day-picker: ^9.11.0
  react-hook-form: 7.63.0
  react-resizable-panels: 3.0.6
  recharts: 2.15.4
  rollup-plugin-typescript2: ^0.36.0
  sonner: 2.0.7
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.13
  tw-animate-css: ^1.3.8
  typescript: ^5.9.3
  vaul: 1.1.2
  vite: ^7.1.9
  vite-plugin-dts: ^4.5.4
  zod: 4.1.8

catalogMode: prefer

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
