packages:
  - apps/*
  - libs/*

catalog:
  '@ai-sdk/google': 2.0.14
  '@ai-sdk/provider': ^2.0.0
  '@eslint/js': ^9.36.0
  '@hono/node-server': ^1.19.3
  '@hookform/resolvers': 5.2.2
  '@modelcontextprotocol/sdk': 1.18.1
  '@radix-ui/react-accordion': ^1.2.12
  '@radix-ui/react-alert-dialog': ^1.1.15
  '@radix-ui/react-aspect-ratio': ^1.1.7
  '@radix-ui/react-avatar': ^1.1.10
  '@radix-ui/react-checkbox': ^1.3.3
  '@radix-ui/react-collapsible': ^1.1.12
  '@radix-ui/react-context-menu': ^2.2.16
  '@radix-ui/react-dialog': ^1.1.15
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-hover-card': ^1.1.15
  '@radix-ui/react-label': ^2.1.7
  '@radix-ui/react-menubar': ^1.1.16
  '@radix-ui/react-navigation-menu': ^1.2.14
  '@radix-ui/react-popover': ^1.1.15
  '@radix-ui/react-progress': ^1.1.7
  '@radix-ui/react-radio-group': ^1.3.8
  '@radix-ui/react-scroll-area': ^1.2.10
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-separator': ^1.1.7
  '@radix-ui/react-slider': ^1.3.6
  '@radix-ui/react-slot': ^1.2.3
  '@radix-ui/react-switch': ^1.2.6
  '@radix-ui/react-tabs': ^1.1.13
  '@radix-ui/react-toggle': ^1.1.10
  '@radix-ui/react-toggle-group': ^1.1.11
  '@radix-ui/react-tooltip': ^1.2.8
  '@tailwindcss/postcss': ^4.1.14
  '@tailwindcss/vite': ^4.0.6
  '@tanstack/eslint-config': ^0.3.2
  '@tanstack/nitro-v2-vite-plugin': ^1.132.40
  '@tanstack/react-devtools': ^0.7.6
  '@tanstack/react-router': ^1.132.47
  '@tanstack/react-router-devtools': ^1.132.51
  '@tanstack/react-router-ssr-query': ^1.132.47
  '@tanstack/react-start': ^1.132.53
  '@tanstack/router-plugin': ^1.132.51
  '@testing-library/dom': ^10.4.0
  '@testing-library/jest-dom': ^6.6.3
  '@types/cookie': ^1.0.0
  '@types/cors': ^2.8.19
  '@types/express': ^5.0.3
  '@types/node': 24.4.0
  '@types/qs': ^6.14.0
  '@typescript-eslint/eslint-plugin': ^8.45.0
  '@typescript-eslint/parser': ^8.45.0
  '@vitejs/plugin-react': ^5.0.4
  ai: 5.0.44
  better-auth: 1.3.26
  bumpp: ^10.1.0
  chalk: ^5.6.2
  class-variance-authority: 0.7.1
  clsx: ^2.1.1
  cmdk: 1.1.1
  cookie: ^1.0.2
  cors: ^2.8.5
  date-fns: 4.1.0
  dotenv: ^17.2.3
  drizzle-kit: ^0.31.4
  drizzle-orm: 0.44.5
  embla-carousel-react: 8.6.0
  eslint: ^9.36.0
  express: ^5.1.0
  globals: ^16.4.0
  happy-dom: ^17.4.6
  hono: ^4.9.7
  input-otp: 1.4.2
  jsdom: ^27.0.0
  lucide-react: ^0.544.0
  motion: 12.23.22
  next-themes: 0.4.6
  postcss: ^8.5.6
  postgres: ^3.4.5
  prettier: ^3.6.2
  qs: ^6.14.0
  react-day-picker: ^9.11.0
  react-hook-form: 7.63.0
  react-resizable-panels: 3.0.6
  recharts: 2.15.4
  sonner: 2.0.7
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.14
  tsup: ^8.5.0
  tsx: ^4.7.1
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  vaul: 1.1.2
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.0.5
  web-vitals: ^5.1.0
  zod: ^4.1.12

catalogMode: prefer

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
