packages:
  - apps/*
  - libs/*

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild

catalogMode: strict
catalog:
  "@types/better-sqlite3": ^7.6.13
  better-sqlite3: ^12.2.0
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.44.5
  typescript: ^5.9.2
