packages:
  - apps/*
  - libs/*

catalog:
  '@eslint/js': ^9.35.0
  '@types/better-sqlite3': ^7.6.13
  '@typescript-eslint/eslint-plugin': ^8.43.0
  '@typescript-eslint/parser': ^8.43.0
  better-sqlite3: ^12.2.0
  drizzle-kit: ^0.31.4
  drizzle-orm: 0.44.5
  eslint: ^9.35.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-prettier: ^5.5.4
  globals: ^16.4.0
  prettier: ^3.6.2
  typescript: ^5.9.2

catalogMode: strict

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
